# FastAPI

Creating RESTful APIs is extremely fast with FastAPI. Pydantic is a technology used for data validation, so you no longer have to create validators manually.

## Setup Instructions

### Create a Virtual Environment

A virtual environment allows you to run the project with all required packages isolated from your system.

1. Create a virtual environment:

   ```bash
   python3 -m venv myenv
   ```

2. Activate the virtual environment:

   ```bash
   source myenv/bin/activate
   ```

3. Verify installed packages:
   ```bash
   pip list
   ```

### Install Dependencies

1. Install FastAPI:

   ```bash
   pip install fastapi
   ```

2. Install Uvicorn (ASGI server):
   ```bash
   pip install uvicorn
   ```

### Create a Simple API

1. Create a file named `books.py`:

   ```python
   from fastapi import FastAPI

   app = FastAPI()

   @app.get("/")
   def read_api():
        return {"Welcome": "Eric"}
   ```

2. Run the server:

   ```bash
   uvicorn books:app --reload
   ```

3. Access the API documentation at `http://127.0.0.1:8000/docs`

## Common HTTP Methods

- **GET**: Read a resource
- **POST**: Create a resource
- **PUT**: Update a resource
- **DELETE**: Delete a resource

## Database Connection

### SQLite Setup on macOS

SQLite is a lightweight SQL database that works great with FastAPI. Follow these steps to install and configure it on macOS using Homebrew.

#### Installation

1. Install Homebrew (if not already installed):

   ```bash
   /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
   ```

2. Close and reopen your terminal, then verify Homebrew installation:

   ```bash
   brew list
   ```

3. Verify SQLite is installed (Homebrew includes it by default):

   ```bash
   sqlite3 --version
   ```

4. Launch SQLite interactive shell:

   ```bash
   sqlite3
   ```

5. Exit the SQLite shell:
   ```bash
   .quit
   ```

#### Using SQLite with FastAPI

Install the required database driver:

```bash
pip install sqlalchemy
```

Create a database connection in your FastAPI app:

```python
from sqlalchemy import create_engine
from sqlalchemy.orm import sessionmaker
from sqlalchemy.ext.declarative import declarative_base

SQLALCHEMY_DATABASE_URL="sqlite:///./books.db"

engine=create_engine(SQLALCHEMY_DATABASE_URL,connect_args={"check_same_thread":False}
)
SessionLocal=sessionmaker(autocommit=False, autoflush=False, bind=engine)
Base=declarative_base()
```

## Project Structure

The repository is organized as follows:

- **`models/` folder**: Contains database models that define the structure of your tables
- **`database.py`**: Defines the database connection and configuration
- **`books.py`**: Contains REST API endpoints with Pydantic validation

## CRUD Operations

All CRUD (Create, Read, Update, Delete) operations are implemented in the `books.py` file where the REST API is written. Pydantic handles data validation automatically.

### Note on IDs

The project uses integer IDs instead of UUIDs. IDs are auto-generated by the database.
